Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: helloworld.StreamLambdaHandler
      CodeUri: C:\Users\lenovo\Desktop\workspace15thMarch\springboot\HelloWorldFunction
      Runtime: java8
      Architectures:
        - x86_64